import Head from "next/head";
import Layout from "../components/layout";
import Box from "../components/box";
import Box2 from "../components/box2";
import {
  FaClock,
  FaUser,
  FaTrash,
  FaShieldAlt,
  FaBuilding,
  FaShoppingCart,
  FaUtensilSpoon,
  FaMoneyBill,
} from "react-icons/fa";
import { GiLift, GiEscalator } from "react-icons/gi";

export default function Test() {
  return (
    <>
      <Head>
        <title>Profile - Masjid Akbar Medhar Arifin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="-z-50 fixed t-0 l-0 w-screen h-screen bg-[url(/profile.jpg)] bg-cover bg-center" />
      <Layout>
        <section className="w-screen flex flex-col justify-center items-center h-screen">
          <p className="textStyle">PEMULIA DAN PEMERSATU UMAT</p>
        </section>
        <Box animate="left">
          <div className="flex bg-[url(/profile1.JPG)] bg-cover bg-center w-[324px] h-[488px] shadow-black shadow-md translate-x-1 rounded-md" />
          <div className="bg-white flex flex-col justify-center items-center w-[324px] h-[440px] px-6 rounded-md">
            <h1 className="text-gold mb-4">Profile</h1>
            <p className="text-center">
              Masjid Akbar Moed’Har Arifin dibangun sebagai
              <br />
              <br />
              sarana ibadah yang representatif bagi karyawan perusahaan,
              masyarakat sekitar dan kaum muslimin pada umumnya.Kapasitas Masjid
              Akbar Moed’Har Arifin mampu menampung hingga 3.000 jamaah,
              tersedia parkir yang luas serta layanan jamaah selama 24 Jam.
              <br />
              <br />
              Penamaan Masjid Akbar Moed’Har Arifin diambil dari nama dua
              bersaudara pendiri PT. Polowijo Gosari. Moed’Har diambil dari nama
              Alm. Achmad Moed’Har Syah (abang) dan Arifin diambil dari nama
              Alm. Achmad Djauhar Arifin (adek).
              <br />
              <br />
              Penamaan tersebut dimaksudkan sebagai pengingat dan motivasi bagi
              generasi penerus dan masyarakat, serta dalam rangka mengenang jasa
              dan kontribusi berliau berdua.
              <br />
              <br />
              Masjid Akbar Moed’Har Arifin dibangun atas prakarsa pendiri dan
              dibiayai sepenuhnya oleh Polowijo Gosari Group melalui Yayasan
              Harfin Gosari.
            </p>
          </div>
        </Box>
        <Box animate="right">
          <div className="bg-white flex flex-col justify-center items-center w-[336px] h-[440px] px-8 rounded-md">
            <h1 className="text-gold mb-4">Sejarah</h1>
            <p className="text-center">
              Sejarah dibangunnya Masjid Akbar Moed’har Arifin bermula atas
              inisiatif dan keinginan lama dari dua tokoh pendiri Polowijo
              Gosari Group,
              <br /> yaitu Bapak H. Achmad Moed’Har Syah (alm.) dan Bapak H.
              Achmad Djauhar Arifin (Alm),
              <br /> namun pembangunan masjid baru bisa dilaksanakan oleh Bapak
              H. Achmad Djauhar Arifin dengan dimulainya pembanguan berupa
              peletakan batu pertama oleh Bapak H. Achmad Djauhar Arifin,
              didampingi Bupati Gresik Bapak Dr. Ir. H. Sambari Halim Radianto,
              ST., Msi., dan Kapolres Gresik AKBP Wahyu Sri Bintoro pada hari
              Jum’at, 11 Mei 2018,
              <br /> dengan mendapat dukungan penuh dari Generasi Penerus (P5)
              dan keluarga besar Polowijo Gosari Group lainnya.
            </p>
          </div>
          <div className="flex bg-[url(/profile2.JPG)] bg-cover bg-center w-[454px] h-[473px] shadow-black shadow-md -translate-x-1 rounded-md" />
        </Box>
        <Box2 image="profile4" animate="left">
          <h1 className="text-gold mb-8 text-xl font-bold">Layanan</h1>
          <div className="grid grid-cols-2 gap-12">
            <div className="flex flex-col justify-center items-center">
              <FaClock className="h-8 w-8 text-white" />
              <p className="text-white">Buka 24 Jam</p>
            </div>
            <div className="flex flex-col justify-center items-center">
              <FaUser className="h-8 w-8 text-white" />
              <p className="text-white">Customer Service</p>
            </div>
            <div className="flex flex-col justify-center items-center">
              <FaTrash className="h-8 w-8 text-white" />
              <p className="text-white">Cleaning Service</p>
            </div>
            <div className="flex flex-col justify-center items-center">
              <FaShieldAlt className="h-8 w-8 text-white" />
              <p className="text-white">Security</p>
            </div>
          </div>
        </Box2>
        <Box2 image="profile3" animate="right">
          <h1 className="text-gold mb-8 text-xl font-bold">Fasilitas</h1>
          <div className="grid grid-cols-2 gap-12">
            <div className="flex flex-col justify-center items-center">
              <FaBuilding className="h-8 w-8 text-white" />
              <p className="text-white">Aula</p>
            </div>
            <div className="flex flex-col justify-center items-center">
              <FaShoppingCart className="h-8 w-8 text-white" />
              <p className="text-white">Harfin Mart</p>
            </div>
            <div className="flex flex-col justify-center items-center">
              <FaUtensilSpoon className="h-8 w-8 text-white" />
              <p className="text-white">Food Court</p>
            </div>
            <div className="flex flex-col justify-center items-center">
              <FaMoneyBill className="h-8 w-8 text-white" />
              <p className="text-white">ATM Center</p>
            </div>
            <div className="flex flex-col justify-center items-center">
              <GiLift className="h-8 w-8 text-white" />
              <p className="text-white">Lift</p>
            </div>
            <div className="flex flex-col justify-center items-center">
              <GiEscalator className="h-8 w-8 text-white" />
              <p className="text-white">Escalator</p>
            </div>
          </div>
        </Box2>
      </Layout>
    </>
  );
}
