import Head from "next/head";
import Layout from "../components/layout";
import Box from "../components/box";

export default function Test() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Layout>
        <Box>
          <h1>Hello</h1>
        </Box>
        <Box>
          <h1>World</h1>
        </Box>
        <Box>
          <h1>React</h1>
        </Box>
      </Layout>
    </>
  );
}
